ALTER TABLE payout ADD COLUMN IF NOT EXISTS account_holder_name VARCHAR(100);
ALTER TABLE payout ADD COLUMN IF NOT EXISTS account_number VARCHAR(100);
ALTER TABLE payout ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR(30);
ALTER TABLE payout ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100);
