package com.foodie.common.enums;

public enum NotificationEventType {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_STATUS_CHANGED,
    ORDER_CANCELLED,
    ORDER_DELIVERED,
    PAYMENT_FAILED,
    REFUND_PROCESSED,
    DELIVERY_PARTNER_ASSIGNED,
    DELIVERY_OFFER,
    RESTAURANT_CREATED,
    RESTAURANT_APPROVED,
    RESTAURANT_SUSPENDED,
    PAYOUT_REQUESTED
}
